### ISSUE TITLE
How do you run it?

### ISSUE THREAD

**Issue by W1MMER** [rpbnz/FlamingoScooterMaps#1]
This seems to be a good script, but I can't figure out how to run it.

This is the issue I'm getting:

<img src="https://i.imgur.com/fQA7AC9.png">

**Comment by rybo-code** [comment]
Looks like you're running on terminal? Works as below through windows command line ![image](https://user-images.githubusercontent.com/89949125/133953625-05d8d9ef-ccd4-432f-99f7-919a88d310e5.png)
Plotting function is basic but could be jazzed up fairly easily. Also script uses geopandas library which can be buggy and is probably not necessary

**Comment by rybo-code** [comment]
Will map as below and saves a csv file for all current stationary scooter locations 
![image](https://user-images.githubusercontent.com/89949125/133953834-96561276-12bd-47e8-a1f9-1f762acf2e71.png)

**Comment by W1MMER** [comment]
Turns out it was an issue with Python, I got it to work in the end. It's a nice tool.
